[project]
name = "whack-a-zombie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.1",
    "pygame-menu>=4.5.1",
    "pygame>=2.6.1",
]
